#!/usr/bin/env bash
# Check if the number of parameters is less than 4 and display usage if so

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
