#!/usr/bin/env bash
# Install and configure Nginx web server

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a custom Nginx index.html file
cat << EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Holberton School</title>
</head>
<body>
    <h1>Holberton School for the win!</h1>
</body>
</html>
EOF

# Restart Nginx
service nginx restart

# Print the status of Nginx
status="$(service nginx status)"
if [[ $status == *"active (running)"* ]]; then
    echo "Nginx is running and listening on port 80."
else
    echo "Nginx failed to start."
fi
