#!/usr/bin/env bash
#setting up nginx server
# Update package index
apt-get update -y

# Install nginx
apt-get install nginx -y

# Replace default nginx index.html with custom content
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html

# Check if nginx is running, if not, start it
if ! ps aux | grep -q [n]ginx; then
    /usr/sbin/nginx
fi

# Check if nginx is listening on port 80, if not, restart it
if ! netstat -tuln | grep -q ':80 '; then
    /usr/sbin/nginx -s stop
    /usr/sbin/nginx
fi
